### ISSUE TITLE
Blank screen 

### ISSUE THREAD

**Issue by rahulsingh303** [sverhoeven/docker-cartodb#70]
When I open the dashboard page i first see a login prompt in left corner of screen ( weird location ) and then after providing user/password it just shows a blank screen , anyone else had this issue ? Using Chrome , but tested with other browsers as well , however in container logs i see this :

`
F, [2019-02-15T17:14:16.368847 #287] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  rollbar (2.11.1) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.11) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.10) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.11) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.11) lib/rack/deflater.rb:35:in `call'
  rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  railties (4.2.10) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.10) lib/rails/railtie.rb:194:in `method_missing'
  thin (1.7.2) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.2) lib/thin/connection.rb:84:in `catch'
  thin (1.7.2) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.2) lib/thin/connection.rb:50:in `block in process'
  eventmachine (1.0.4) lib/eventmachine.rb:1046:in `block in spawn_threadpool'
`
Does above error makes any sense to anyone , please help .

-Rahul

**Comment by mbforr** [comment]
getting the same issue here as well. saw css and js files are not loading and tried the fix listed here as well with no luck:

https://github.com/sverhoeven/docker-cartodb/issues/65

**Comment by Baschdl** [comment]
Did you use the standard hostname? cartodb.localhost did not work for me on MacOS

**Comment by Stivens73** [comment]
Just faced the same issue #91 . Was running this container on EC2 instance and did not have an actual domain name. After starting container with `-h ip-address` the issue was resolved. Hope it helps.
